kind: pipeline
type: docker
name: default

steps:
- name: build-and-pub-oci-image
  image: plugins/docker
  settings:
    context: .
    dockerfile: Containerfile
    tags: 
      - latest
      - ${DRONE_TAG}
    repo: jjtc/steam-wine-xvfb
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  
trigger:
  event:
  - tag
